require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'chikaApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn', '~> 5.0.2'

  target 'chikaAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  #pod 'NMapsMap'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'chikaApp-tvOS' do
  # Pods for chikaApp-tvOS

  target 'chikaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
