require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'chikaApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'Firebase/Analytics'
  pod 'GoogleSignIn', '~> 5.0.2'

  pod 'RNConvertPhAsset', :path => '../node_modules/react-native-convert-ph-asset'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'


  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-nmap', :path => '../node_modules/react-native-nmap'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'chikaAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  #pod 'NMapsMap'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
end

target 'chikaApp-tvOS' do
  # Pods for chikaApp-tvOS

  target 'chikaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
